### ISSUE TITLE
No podspec found for `simdjson` in `./node_modules/@nozbe/simdjson`

### ISSUE THREAD

**Issue by theianjohnson** [skam22/watermelondb-expo-plugin#14]
Tried following the readme to add this into a new expo project and when running `npx expo run:ios` I'm getting

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: No podspec found for `simdjson` in `./node_modules/@nozbe/simdjson`

I've tried changing that path in `app.json` to multiple variations of `./node_modules`, `/node_modules`, `node_modules` etc and same error

**Comment by skam22** [comment]
Can you compare your folder structure to the /example/ project and let me know where it’s different?

**Comment by theianjohnson** [comment]
Got it compiling! I changed the path to match your example project, ie `"path": "../node_modules/@nozbe/simdjson",` from the readme (`"path": "path_to/node_modules/@nozbe/simdjson",`). I would never have guessed from app.json to node_modules was `../`

**Comment by skam22** [comment]
Awesome
