### ISSUE TITLE
Error: "could not find a copy of expo to link"

### ISSUE THREAD

**Issue by PEZO19** [skam22/watermelondb-expo-plugin#19]
After deleting `node_modules` as a whole, this error occures after `yarn`.
> error An unexpected error occurred: "could not find a copy of expo to link in <yourPath>/@skam22/watermelondb-expo-plugin/node_modules".

This workaround was ok for me:
1. remove `"@skam22/watermelondb-expo-plugin": "1.0.1",` from `package.json`
2. `yarn`
3. readd to `package.json`
4. `yarn`

**Comment by skam22** [comment]
please update from version 1.0.1

**Comment by PEZO19** [comment]
@skam22 Will come back to this when I update Expo SDK if that's ok. I close it until.
