### ISSUE TITLE
Does not work with expo v49

### ISSUE THREAD

**Issue by PEZO19** [skam22/watermelondb-expo-plugin#8]
Hi there! Thanks for the plugin, works well with expo v48, however I get the following after upgrading to v49. 

`yarn` (to upgrade to v49)
`yarn ios`

> CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
To view more error logs, try building the app with Xcode directly, by opening /Users/youser/ExpoApp/ios/example.xcodeproj.

I tried to remove `node_modules` and `ios` folders and rerun but without success. 

Does it work for you?

**Comment by skam22** [comment]
I haven’t tried it with Expo SDK 49. 

Will check it when I get some time and I’ll let you know.

**Comment by skam22** [comment]
@PEZO19 

updated the example for expo sdk 49 support.  I confirmed that it works perfectly.

**Comment by PEZO19** [comment]
@skam22 Thanks a lot! Will check soon!
