### ISSUE TITLE
Error with Expo 49 -  No matching configuration of project :watermelondb-jsi was found.

### ISSUE THREAD

**Issue by octalpixel** [skam22/watermelondb-expo-plugin#9]
Getting the following error when trying to build an expo dev client.  Any thoughts ?

"Install Android SDK Platform 33 (revision: 3)" complete.

"Install Android SDK Platform 33 (revision: 3)" finished.

[stderr] 

FAILURE: Build failed with an exception.

[stderr] 

* What went wrong:

[stderr] 

Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.

[stderr] 

> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.

[stderr] 

   > Could not resolve project :watermelondb-jsi.

[stderr] 

     Required by:

[stderr] 

         project :app

[stderr] 

      >

[stderr] 

No matching configuration of project :watermelondb-jsi was found. The consumer was configured to find a component for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2' but:

[stderr] 

          - None of the consumable configurations have attributes.

[stderr] 

* Try:

[stderr] 

> Run with --stacktrace option to get the stack trace.

[stderr] 

> Run with --info or --debug option to get more log output.

[stderr] 

> Run with --scan to get full insights.

[stderr] 

* Get more help at https://help.gradle.org

[stderr] 

BUILD FAILED in 3m 45s

**Comment by skam22** [comment]
What does settings.gradle look like after running a prebuild?

**Comment by octalpixel** [comment]
> What does settings.gradle look like after running a prebuild?

I am unable to prebuild. Throws and error for that as well.

**Comment by skam22** [comment]
If you put together a snack I’ll take a look. Would suggest you look at the example project to see the differences between your project and the example (which works correctly).

**Comment by skam22** [comment]
@octalpixel closing this issue for now - if you're still having problems let me know.

**Comment by jamessonlps** [comment]
I tried to use it on Android with Expo 49, but I got the following error when running the application:

`TypeError: Cannot read property 'initializeJSI' of null, js engine: hermes`

What could be the reason for this?
